version: '3'
services:
  mongodb:
    image: mongo:4.2.22
    ports:
      - 27017:27017
  application:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    links:
      - mongodb
  
